DROP TABLE NACAO CASCADE CONSTRAINTS;
DROP TABLE MODALIDADE CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANTE CASCADE CONSTRAINTS;
DROP TABLE TELEFONES CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE PREPARADOR CASCADE CONSTRAINTS;
DROP TABLE ATLETA CASCADE CONSTRAINTS;
DROP TABLE ROTINA CASCADE CONSTRAINTS;
DROP TABLE PREPARO CASCADE CONSTRAINTS;
DROP TABLE RECUPERACAO CASCADE CONSTRAINTS;
DROP TABLE LESAO CASCADE CONSTRAINTS;
DROP TABLE ATENDIMENTO_LESAO CASCADE CONSTRAINTS;
DROP TABLE ATENDIMENTO_DOPING CASCADE CONSTRAINTS;
DROP TABLE ATENDIMENTO_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE SINTOMAS CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE METODO CASCADE CONSTRAINTS;

CREATE TABLE NACAO (
    NroNacao NUMBER(6)  NOT NULL, 
    Nome VARCHAR2(100)  NOT NULL,
    Continente VARCHAR2(20) NOT NULL,
    NumAtletas NUMBER(6),
    Esporte VARCHAR(20),
    Bandeira bfile,
    Hino VARCHAR2(2000),
    
    CONSTRAINT PKNACAO PRIMARY KEY (NroNacao),
    CONSTRAINT UNNOMENACAO UNIQUE (Nome)
);

CREATE TABLE MODALIDADE (
    NroModalidade NUMBER(6) NOT NULL,
    Nome VARCHAR2(100)      NOT NULL,
    Descricao VARCHAR2(1000),
    
    CONSTRAINT PKMODALIDADE PRIMARY KEY (NroModalidade),
    CONSTRAINT UNNOMEMODALIDADE UNIQUE (Nome)    
);

CREATE TABLE PARTICIPANTE (
    NroPar NUMBER(6) NOT NULL,
    Nome VARCHAR2(100) NOT NULL,
    Tipo VARCHAR2(10) NOT NULL,
    
    CONSTRAINT PKPARTICIPANTE PRIMARY KEY (NroPar),
    CONSTRAINT UNNOMEPARTICIPANTE UNIQUE (Nome),
    CONSTRAINT CKTIPOPARTICIPANTE CHECK (Tipo IN ('atleta', 'preparador', 'medico'))
);

CREATE TABLE TELEFONES (
    CodigoPar NUMBER(6) NOT NULL,
    Numero NUMBER(20)   NOT NULL,
    
    CONSTRAINT PKTELEFONES PRIMARY KEY (CodigoPar, Numero),
    CONSTRAINT FKTELEFONESPARTICIPANTE FOREIGN KEY (CodigoPar)
        REFERENCES PARTICIPANTE(NroPar) ON DELETE CASCADE
);

CREATE TABLE MEDICO (
    NroMedico NUMBER(6) NOT NULL,
    CRM NUMBER(10) NOT NULL, 
    Endereco VARCHAR2(100),
 
    CONSTRAINT PKMEDICO PRIMARY KEY (NroMedico),
    CONSTRAINT FKMEDICOPARTICIPANTE FOREIGN KEY (NroMedico)
        REFERENCES PARTICIPANTE(NroPar) ON DELETE CASCADE,
    CONSTRAINT UNCRMMEDICO UNIQUE (CRM)
);

CREATE TABLE PREPARADOR (
    NroPreparador NUMBER(6) NOT NULL,
    Email VARCHAR2(50)  NOT NULL, 
    Senha VARCHAR2(50)  NOT NULL,
    Cidade VARCHAR2(50),
    Estado VARCHAR2(50),
    Nacao NUMBER(6),
    Data_Nasc DATE,
    Sexo VARCHAR2(10),
    TipoIdent CHAR(3)   NOT NULL,
    CPF VARCHAR2(50),
    Passaporte VARCHAR2(50),
    
    CONSTRAINT PKPREPARADOR PRIMARY KEY (NroPreparador),
    CONSTRAINT FKPREPARADORPARTICIPANTE FOREIGN KEY (NroPreparador)
        REFERENCES PARTICIPANTE(NroPar) ON DELETE CASCADE,
    CONSTRAINT UNEMAILPREPARADOR UNIQUE (Email),
    CONSTRAINT UNCPFPREPARADOR UNIQUE (CPF),
    CONSTRAINT UNPASSAPORTEPREPARADOR UNIQUE (Passaporte),
    CONSTRAINT CKSEXOPREPARADOR CHECK (Sexo IN ('feminino', 'masculino')),
    CONSTRAINT CKTIPOIDENTIDADEPREPARADOR CHECK (
    TipoIdent = 'bra' AND CPF IS NOT NULL
    OR
    TipoIdent = 'est' AND Passaporte IS NOT NULL)
);

CREATE TABLE ATLETA (
    NroAtleta NUMBER(6) NOT NULL,
    Situacao VARCHAR2(10),
    Passaporte VARCHAR2(50)  NOT NULL,
    Sexo VARCHAR2(10)   NOT NULL,
    Peso FLOAT,
    Altura FLOAT,
    Data_Nasc DATE,
    Preparador NUMBER(6) NOT NULL,
    Nacao NUMBER(6)    NOT NULL,
    Modalidade NUMBER(6) NOT NULL,
    
    CONSTRAINT PKATLETA PRIMARY KEY (NroAtleta),
    CONSTRAINT UNPASSAPORTEATLETA UNIQUE (Passaporte),
    CONSTRAINT FKATLETAPARTICIPANTE FOREIGN KEY (NroAtleta)
        REFERENCES PARTICIPANTE(NroPar) ON DELETE CASCADE,
        
    CONSTRAINT CKSITUACAOATLETA CHECK (Situacao IN ('regular', 'suspenso', 'recuperado')),
    CONSTRAINT CKSEXOATLETA CHECK (Sexo IN ('feminino','masculino'))
);

CREATE TABLE ROTINA (
    NroRotina NUMBER(6) NOT NULL,
    Preparador NUMBER(6)    NOT NULL,
    DiaSemana VARCHAR2(10)  NOT NULL,
    Repeticao NUMBER(3) DEFAULT 1 NOT NULL,
    Descricao VARCHAR2(1000) NOT NULL,
    Atleta NUMBER(6)    NOT NULL,
    
    CONSTRAINT PKROTINA PRIMARY KEY (NroRotina),
    CONSTRAINT UNROTINA UNIQUE (Preparador, DiaSemana),
    CONSTRAINT FKROTINAPREPARADOR FOREIGN KEY (Preparador)
        REFERENCES PREPARADOR(NroPreparador) ON DELETE CASCADE,
    CONSTRAINT FKROTINAATLETA FOREIGN KEY (Atleta)
        REFERENCES ATLETA(NroAtleta) ON DELETE CASCADE
);

CREATE TABLE PREPARO (
    NroPreparo NUMBER(6) NOT NULL,
    Rotina NUMBER(6)    NOT NULL,
    Descricao VARCHAR2(1000) NOT NULL,
    
    CONSTRAINT PKPREPARO PRIMARY KEY (NroPreparo),
    CONSTRAINT FKPREPAROROTINA FOREIGN KEY (Rotina)
        REFERENCES ROTINA(NroRotina) ON DELETE CASCADE
);

CREATE TABLE RECUPERACAO (
    NroRecuperacao NUMBER(6)    NOT NULL,
    Rotina NUMBER(6)    NOT NULL,
    Descricao VARCHAR2(1000) NOT NULL,
    
    CONSTRAINT PKRECUPERACAO PRIMARY KEY (NroRecuperacao),
    CONSTRAINT FKRECUPERACAOROTINA FOREIGN KEY (Rotina)
        REFERENCES ROTINA(NroRotina) ON DELETE CASCADE
);

CREATE TABLE LESAO (
    NroLesao NUMBER(6)  NOT NULL,
    Descricao VARCHAR2(1000)     NOT NULL,
    
    CONSTRAINT PKLESAO PRIMARY KEY (NroLesao)
);

CREATE TABLE ATENDIMENTO_LESAO (
    Atleta NUMBER(6)    NOT NULL,
    Lesao NUMBER(6)     NOT NULL,
    Medico NUMBER(6)    NOT NULL,
    
    CONSTRAINT PKATENDIMENTO_LESAO PRIMARY KEY (Atleta, Lesao),
    CONSTRAINT FKATENDIMENTOLESAO_ATLETA FOREIGN KEY (Atleta)
        REFERENCES ATLETA(NroAtleta) ON DELETE CASCADE,
    CONSTRAINT FKATENDIMENTOLESAO_LESAO FOREIGN KEY (Lesao)
        REFERENCES LESAO(NroLesao) ON DELETE CASCADE,
    CONSTRAINT FKATENDIMENTOLESAO_MEDICO FOREIGN KEY (Medico)
        REFERENCES MEDICO(NroMedico) ON DELETE CASCADE
);

CREATE TABLE ATENDIMENTO_DOPING (
    NroDoping NUMBER(6) NOT NULL,
    Atleta NUMBER(6)    NOT NULL,
    Medico NUMBER(6)    NOT NULL,
    Data DATE           NOT NULL,
    Resultados VARCHAR2(100)    NOT NULL,
    NroIrregularidades NUMBER(1) DEFAULT 0 NOT NULL,
    
    CONSTRAINT PKDOPING PRIMARY KEY (NroDoping),
    CONSTRAINT UNDOPING UNIQUE (Atleta, Medico, Data),
    CONSTRAINT FKDOPINGATELTA FOREIGN KEY (Atleta)
        REFERENCES ATLETA(NroAtleta) ON DELETE CASCADE,
    CONSTRAINT FKDOPINGMEDICO FOREIGN KEY (Medico)
        REFERENCES MEDICO(NroMedico) ON DELETE CASCADE
);

CREATE TABLE ATENDIMENTO_CONSULTA (
    NroConsulta NUMBER(6) NOT NULL,
    Atleta NUMBER(6)    NOT NULL,
    Medico NUMBER(6)    NOT NULL,
    Data DATE           NOT NULL,
    
    CONSTRAINT PKCONSULTA PRIMARY KEY (NroConsulta),
    CONSTRAINT UNCONSULTA UNIQUE (Atleta, Medico, Data),
    CONSTRAINT FKCONSULTAATLETA FOREIGN KEY (Atleta)
        REFERENCES ATLETA(NroAtleta) ON DELETE CASCADE,
    CONSTRAINT FKCONSULTAMEDICO FOREIGN KEY (Medico)
        REFERENCES MEDICO(NroMedico) ON DELETE CASCADE
);

CREATE TABLE SINTOMAS (
    CodConsulta NUMBER(6)    NOT NULL,
    Sintoma VARCHAR2(1000) NOT NULL,
    
    CONSTRAINT PKSINTOMAS PRIMARY KEY (CodConsulta, Sintoma),
    CONSTRAINT FKSINTOMASCONSULTA FOREIGN KEY (CodConsulta)
        REFERENCES ATENDIMENTO_CONSULTA(NroConsulta) ON DELETE CASCADE
);

CREATE TABLE DIAGNOSTICO (
    NroDiag NUMBER(6)   NOT NULL,
    Consulta NUMBER(6)  NOT NULL,
    Descricao   VARCHAR2(1000)   NOT NULL,
    
    CONSTRAINT PKDIAGNOSTICO PRIMARY KEY (NroDiag),
    CONSTRAINT FKDIAGNOSTICOCONSULTA FOREIGN KEY (Consulta)
        REFERENCES ATENDIMENTO_CONSULTA(NroConsulta) ON DELETE CASCADE
);

CREATE TABLE METODO (
    NroMetodo NUMBER(6) NOT NULL,
    Diagnostico NUMBER(6)   NOT NULL,
    Descricao VARCHAR2(1000) NOT NULL,
    Efetividade VARCHAR2(1000)   NOT NULL,
    
    CONSTRAINT PKMETODO PRIMARY KEY (NroMetodo),
    CONSTRAINT FKMETODODIAGNOSTICO FOREIGN KEY (Diagnostico)
        REFERENCES DIAGNOSTICO(NroDiag) ON DELETE CASCADE
);